// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dns "github.com/metal-stack/firewall-controller/v2/pkg/dns"
	mock "github.com/stretchr/testify/mock"

	v1 "github.com/metal-stack/firewall-controller/v2/api/v1"
)

// FQDNCache is an autogenerated mock type for the FQDNCache type
type FQDNCache struct {
	mock.Mock
}

// CacheAddr provides a mock function with no fields
func (_m *FQDNCache) CacheAddr() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for CacheAddr")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSetsForFQDN provides a mock function with given fields: fqdn
func (_m *FQDNCache) GetSetsForFQDN(fqdn v1.FQDNSelector) []v1.IPSet {
	ret := _m.Called(fqdn)

	if len(ret) == 0 {
		panic("no return value specified for GetSetsForFQDN")
	}

	var r0 []v1.IPSet
	if rf, ok := ret.Get(0).(func(v1.FQDNSelector) []v1.IPSet); ok {
		r0 = rf(fqdn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.IPSet)
		}
	}

	return r0
}

// GetSetsForRendering provides a mock function with given fields: fqdns
func (_m *FQDNCache) GetSetsForRendering(fqdns []v1.FQDNSelector) []dns.RenderIPSet {
	ret := _m.Called(fqdns)

	if len(ret) == 0 {
		panic("no return value specified for GetSetsForRendering")
	}

	var r0 []dns.RenderIPSet
	if rf, ok := ret.Get(0).(func([]v1.FQDNSelector) []dns.RenderIPSet); ok {
		r0 = rf(fqdns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dns.RenderIPSet)
		}
	}

	return r0
}

// IsInitialized provides a mock function with no fields
func (_m *FQDNCache) IsInitialized() bool {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInitialized")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewFQDNCache creates a new instance of FQDNCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFQDNCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *FQDNCache {
	mock := &FQDNCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
