---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - metal-stack.io
  resources:
  - clusterwidenetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal-stack.io
  resources:
  - clusterwidenetworkpolicies/status
  verbs:
  - get
  - patch
  - update
