// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package nftables

import (
	"github.com/metal-stack/firewall-controller/v2/api/v1"
	"github.com/metal-stack/firewall-controller/v2/pkg/dns"
	mock "github.com/stretchr/testify/mock"
)

// NewFQDNCache creates a new instance of FQDNCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFQDNCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *FQDNCache {
	mock := &FQDNCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// FQDNCache is an autogenerated mock type for the FQDNCache type
type FQDNCache struct {
	mock.Mock
}

type FQDNCache_Expecter struct {
	mock *mock.Mock
}

func (_m *FQDNCache) EXPECT() *FQDNCache_Expecter {
	return &FQDNCache_Expecter{mock: &_m.Mock}
}

// CacheAddr provides a mock function for the type FQDNCache
func (_mock *FQDNCache) CacheAddr() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CacheAddr")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// FQDNCache_CacheAddr_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CacheAddr'
type FQDNCache_CacheAddr_Call struct {
	*mock.Call
}

// CacheAddr is a helper method to define mock.On call
func (_e *FQDNCache_Expecter) CacheAddr() *FQDNCache_CacheAddr_Call {
	return &FQDNCache_CacheAddr_Call{Call: _e.mock.On("CacheAddr")}
}

func (_c *FQDNCache_CacheAddr_Call) Run(run func()) *FQDNCache_CacheAddr_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FQDNCache_CacheAddr_Call) Return(s string) *FQDNCache_CacheAddr_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *FQDNCache_CacheAddr_Call) RunAndReturn(run func() string) *FQDNCache_CacheAddr_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetsForFQDN provides a mock function for the type FQDNCache
func (_mock *FQDNCache) GetSetsForFQDN(fqdn v1.FQDNSelector) []v1.IPSet {
	ret := _mock.Called(fqdn)

	if len(ret) == 0 {
		panic("no return value specified for GetSetsForFQDN")
	}

	var r0 []v1.IPSet
	if returnFunc, ok := ret.Get(0).(func(v1.FQDNSelector) []v1.IPSet); ok {
		r0 = returnFunc(fqdn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.IPSet)
		}
	}
	return r0
}

// FQDNCache_GetSetsForFQDN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetsForFQDN'
type FQDNCache_GetSetsForFQDN_Call struct {
	*mock.Call
}

// GetSetsForFQDN is a helper method to define mock.On call
//   - fqdn v1.FQDNSelector
func (_e *FQDNCache_Expecter) GetSetsForFQDN(fqdn interface{}) *FQDNCache_GetSetsForFQDN_Call {
	return &FQDNCache_GetSetsForFQDN_Call{Call: _e.mock.On("GetSetsForFQDN", fqdn)}
}

func (_c *FQDNCache_GetSetsForFQDN_Call) Run(run func(fqdn v1.FQDNSelector)) *FQDNCache_GetSetsForFQDN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 v1.FQDNSelector
		if args[0] != nil {
			arg0 = args[0].(v1.FQDNSelector)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FQDNCache_GetSetsForFQDN_Call) Return(result []v1.IPSet) *FQDNCache_GetSetsForFQDN_Call {
	_c.Call.Return(result)
	return _c
}

func (_c *FQDNCache_GetSetsForFQDN_Call) RunAndReturn(run func(fqdn v1.FQDNSelector) []v1.IPSet) *FQDNCache_GetSetsForFQDN_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetsForRendering provides a mock function for the type FQDNCache
func (_mock *FQDNCache) GetSetsForRendering(fqdns []v1.FQDNSelector) []dns.RenderIPSet {
	ret := _mock.Called(fqdns)

	if len(ret) == 0 {
		panic("no return value specified for GetSetsForRendering")
	}

	var r0 []dns.RenderIPSet
	if returnFunc, ok := ret.Get(0).(func([]v1.FQDNSelector) []dns.RenderIPSet); ok {
		r0 = returnFunc(fqdns)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dns.RenderIPSet)
		}
	}
	return r0
}

// FQDNCache_GetSetsForRendering_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetsForRendering'
type FQDNCache_GetSetsForRendering_Call struct {
	*mock.Call
}

// GetSetsForRendering is a helper method to define mock.On call
//   - fqdns []v1.FQDNSelector
func (_e *FQDNCache_Expecter) GetSetsForRendering(fqdns interface{}) *FQDNCache_GetSetsForRendering_Call {
	return &FQDNCache_GetSetsForRendering_Call{Call: _e.mock.On("GetSetsForRendering", fqdns)}
}

func (_c *FQDNCache_GetSetsForRendering_Call) Run(run func(fqdns []v1.FQDNSelector)) *FQDNCache_GetSetsForRendering_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []v1.FQDNSelector
		if args[0] != nil {
			arg0 = args[0].([]v1.FQDNSelector)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *FQDNCache_GetSetsForRendering_Call) Return(result []dns.RenderIPSet) *FQDNCache_GetSetsForRendering_Call {
	_c.Call.Return(result)
	return _c
}

func (_c *FQDNCache_GetSetsForRendering_Call) RunAndReturn(run func(fqdns []v1.FQDNSelector) []dns.RenderIPSet) *FQDNCache_GetSetsForRendering_Call {
	_c.Call.Return(run)
	return _c
}

// IsInitialized provides a mock function for the type FQDNCache
func (_mock *FQDNCache) IsInitialized() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsInitialized")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// FQDNCache_IsInitialized_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsInitialized'
type FQDNCache_IsInitialized_Call struct {
	*mock.Call
}

// IsInitialized is a helper method to define mock.On call
func (_e *FQDNCache_Expecter) IsInitialized() *FQDNCache_IsInitialized_Call {
	return &FQDNCache_IsInitialized_Call{Call: _e.mock.On("IsInitialized")}
}

func (_c *FQDNCache_IsInitialized_Call) Run(run func()) *FQDNCache_IsInitialized_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *FQDNCache_IsInitialized_Call) Return(b bool) *FQDNCache_IsInitialized_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *FQDNCache_IsInitialized_Call) RunAndReturn(run func() bool) *FQDNCache_IsInitialized_Call {
	_c.Call.Return(run)
	return _c
}
