name: Build latest image

on:
  push:
    branches:
      - master

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.x'

    - name: run integration tests
      run: |
        sudo apt install -y --no-install-recommends nftables iproute2 kmod
        sudo modprobe dummy
        sudo ip link add vrf42 type dummy
        sudo ip link add vlan42 type dummy
        export KUBEBUILDER_ASSETS=/usr/local/bin
        sudo "PATH=$PATH" --preserve-env=GOROOT make test-all clean

  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: '1.17.x'

    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}

    - name: Build
      run: |
        make fetch-template

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: -p bugs -p unused --timeout=3m

    - name: Build
      run: |
        make

    - name: Build and Push Docker Image
      run: |
        make docker-build
        make docker-push

    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
