name: Docker Image from master

on:
  push:
    branches:
      - master

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: run integration tests
      run: |
        sudo apt install -y --no-install-recommends nftables iproute2 kmod
        sudo modprobe dummy
        sudo ip link add vrf42 type dummy
        sudo ip link add vlan42 type dummy
        sudo make test-all clean
  build:
    needs: integration
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: build the Docker images
      run: |
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        make docker-build
        make docker-push
