name: Docker Image from master

on:
  push:
    branches:
      - master

jobs:
  integration:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: run integration tests
      run: |
        sudo apt install -y --no-install-recommends nftables iproute2 kmod
        sudo modprobe dummy
        sudo ip link add vrf42 type dummy
        sudo ip link add vlan42 type dummy
        sudo make test-all clean
  build:
    needs: integration
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USER }}
        password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
    - name: build the Docker images
      run: |
        make docker-build
        make docker-push
